on: [pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: echo "${{ github.head_ref }}"
      - run: echo "contains"
        if: contains( github.head_ref, 'test-branch2' )
      - run: echo "contains 2"
        if: ${{ contains(github.head_ref, 'test-branch2') }}
      - run: echo ${{ github.sha }}
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.event }}
      - run: echo ${{ github.event.pull_request }}
      - run: echo ${{ github.event.pull_request.user }}
      - run: echo ${{ github.event.pull_request.user.login }}
      - name: Set some template variables
        id: vars
        run: |
          echo ::set-output name=today::"$(date +%d-%m-%Y)"
      - name: set env vars
        run: |
          MULTILINE_BANANA=$(cat banana/2.txt)
          echo "MULTILINE_BANANA<<EOF" >> $GITHUB_ENV
          echo "$MULTILINE_BANANA" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: angelikatyborska/pr-commenter-action@1a0999f18f7eb1b9042a9eac2fac99d2c7d1d4d8
        with:
          template-variables: |
            { "prAuthor": "" }
