on: [pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"
      - run: echo "contains"
        if: contains( github.head_ref, 'test-branch' )
      - run: echo "contains 2"
        if: ${{ contains(github.head_ref, 'test-branch') }}
      - run: echo ${{ github.sha }}
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.event }}
      - run: echo ${{ github.event.pull_request }}
      - run: echo ${{ github.event.pull_request.user }}
      - run: echo ${{ github.event.pull_request.user.login }}
      - name: Set some template variables
        id: vars
        run: |
          echo ::set-output name=today::"$(date +%d-%m-%Y)"
      - uses: angelikatyborska/pr-commenter-action@76bcbafd269c4990f79dfef8d4e5253932636a74
        with:
          template-variables: |
            {
              "today": "${{ steps.vars.outputs.today }}",
              "prAuthor": "${{ github.event.pull_request.user.login }}",
              "prBranchNameStartsWithRequiredPrefix": ${{ startsWith(github.event.pull_request.head.ref, 'test-') }}
            }
