on: [pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: angelikatyborska/pr-commenter-action@76bcbafd269c4990f79dfef8d4e5253932636a74
        with:
          template-variables: |
            {
              "name": "Angelika"
            }
